#!/usr/bin/env python3
"""seed_hires_sheets.py

Generates three placeholder spritesheets for hi-res item icons:

  assets/icons/hires/weapons.png  —  20 weapon-slot items  (8×3 grid, 64×64 px each)
  assets/icons/hires/armor.png    —  13 armor-slot items   (8×2 grid)
  assets/icons/hires/items.png    —  11 resource/misc items(8×2 grid)

Then patches resources/items.json to add `hires_sheet` and `hires_cell`
to every item so the game already knows which cell on which sheet to use.
Any old single-item PNGs generated by the previous seed script are removed.

When you replace the placeholder sheets with real art (same layout, same
tile size), the items automatically pick up the new icons — no code change
needed.

Run from the repo root:
    python3 tools/seed_hires_sheets.py

Requires: Pillow  (pip install Pillow)
"""

import json
import os
import re
import shutil
from pathlib import Path

try:
    from PIL import Image, ImageDraw, ImageFont
except ImportError:
    raise SystemExit("Pillow is required: pip install Pillow")

# ── Paths ────────────────────────────────────────────────────────────────────
REPO      = Path(__file__).resolve().parents[1]
ITEMS_JSON = REPO / "resources" / "items.json"
HIRES_DIR  = REPO / "assets" / "icons" / "hires"

TILE = 64    # px per tile
COLS = 8     # columns on every sheet

# ── Category background colours (R, G, B) ────────────────────────────────────
CAT_COLORS = {
    "weapons": (100, 45,  45),   # dark crimson
    "armor":   (40,  65, 110),   # steel blue
    "items":   (45,  95,  55),   # forest green
}

# ── Helpers ───────────────────────────────────────────────────────────────────

def resolve_slot(items: dict, id: str, visited: set = None) -> str:
    """Walk the parent chain to find the effective slot of an item."""
    if visited is None:
        visited = set()
    if id in visited:
        return "none"
    visited.add(id)
    data = items.get(id, {})
    if "slot" in data:
        return data["slot"]
    parent = data.get("parent", "")
    if parent:
        return resolve_slot(items, parent, visited)
    return "none"


def categorize(items: dict) -> dict:
    """Return a dict of {category: [sorted item ids]}."""
    armor_slots = {"head", "body", "feet", "off_hand"}
    cats = {"weapons": [], "armor": [], "items": []}
    for id in sorted(items):
        slot = resolve_slot(items, id)
        if slot == "weapon":
            cats["weapons"].append(id)
        elif slot in armor_slots:
            cats["armor"].append(id)
        else:
            cats["items"].append(id)
    return cats


def make_tile(item_id: str, cat: str, index: int, total: int) -> Image.Image:
    """Render a single 64×64 placeholder tile."""
    bg = CAT_COLORS[cat]
    img = Image.new("RGBA", (TILE, TILE), (*bg, 255))
    draw = ImageDraw.Draw(img)

    # Slightly lighter inner fill to give depth.
    inner_bg = tuple(min(255, int(c * 1.25)) for c in bg) + (255,)
    draw.rectangle([3, 3, TILE - 4, TILE - 4], fill=inner_bg)

    # Dark border.
    bc = tuple(max(0, int(c * 0.55)) for c in bg) + (255,)
    draw.rectangle([0, 0, TILE - 1, TILE - 1], outline=bc, width=3)

    # Small index number in top-right corner.
    try:
        num_font = ImageFont.truetype(
            "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf", 8)
    except Exception:
        num_font = ImageFont.load_default()
    draw.text((TILE - 14, 3), str(index), font=num_font, fill=(180, 180, 180, 200))

    # Item name, wrapped to two lines.
    words = item_id.split("_")
    if len(words) == 1:
        label = item_id
    elif len(words) == 2:
        label = words[0] + "\n" + words[1]
    else:
        label = words[0] + "\n" + "_".join(words[1:])

    # Pick a font; fall back to default.
    font = None
    for fp in [
        "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    ]:
        if os.path.exists(fp):
            try:
                font = ImageFont.truetype(fp, 10)
                break
            except Exception:
                pass
    if font is None:
        font = ImageFont.load_default()

    bbox = draw.textbbox((0, 0), label, font=font)
    tw = bbox[2] - bbox[0]
    th = bbox[3] - bbox[1]
    tx = (TILE - tw) // 2
    ty = (TILE - th) // 2 - bbox[1]

    # Shadow
    draw.multiline_text((tx + 1, ty + 1), label, font=font,
                        fill=(0, 0, 0, 180), align="center")
    # Label
    draw.multiline_text((tx, ty), label, font=font,
                        fill=(235, 235, 235, 255), align="center")
    return img


def build_sheet(item_ids: list, cat: str) -> tuple:
    """Build sheet PNG + {id: [col, row]} mapping dict."""
    rows = (len(item_ids) + COLS - 1) // COLS
    w = COLS * TILE
    h = rows * TILE
    sheet = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    mapping = {}
    for i, id in enumerate(item_ids):
        col = i % COLS
        row = i // COLS
        tile = make_tile(id, cat, i, len(item_ids))
        sheet.paste(tile, (col * TILE, row * TILE))
        mapping[id] = [col, row]
    return sheet, mapping


def clean_old_individuals(hires_dir: Path, keep_names: set) -> None:
    """Remove any *.png in hires_dir that are NOT in keep_names."""
    for p in hires_dir.glob("*.png"):
        if p.name not in keep_names:
            p.unlink()
            print(f"    removed old individual PNG: {p.name}")


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    with open(ITEMS_JSON, encoding="utf-8") as f:
        items = json.load(f)

    cats = categorize(items)
    print("Sheet layout:")
    for cat, ids in cats.items():
        rows = (len(ids) + COLS - 1) // COLS
        print(f"  {cat}.png  —  {len(ids)} items  ({COLS}×{rows} grid, "
              f"{COLS * TILE}×{rows * TILE} px)")

    HIRES_DIR.mkdir(parents=True, exist_ok=True)

    # Build + save each sheet; collect all cell mappings.
    sheet_pngs: set = set()
    all_mappings: dict = {}          # id → (sheet_name, [col, row])

    for cat, ids in cats.items():
        sheet, mapping = build_sheet(ids, cat)
        out_path = HIRES_DIR / f"{cat}.png"
        sheet.save(str(out_path))
        print(f"  saved  {out_path.name}  ({sheet.width}×{sheet.height})")
        sheet_pngs.add(f"{cat}.png")
        for id, cell in mapping.items():
            all_mappings[id] = (cat, cell)

    # Remove any stale individual-icon PNGs from the old approach.
    clean_old_individuals(HIRES_DIR, sheet_pngs)

    # Ensure _spec.json exists and has the right tile size.
    spec_path = HIRES_DIR / "_spec.json"
    if not spec_path.exists():
        spec_path.write_text('{ "tile_px": 64, "margin_px": 0 }\n', encoding="utf-8")
        print(f"  created _spec.json")

    # Patch items.json — add hires_sheet + hires_cell to every item entry.
    changed = 0
    for id, (sheet_name, cell) in all_mappings.items():
        if id in items:
            items[id]["hires_sheet"] = sheet_name
            items[id]["hires_cell"] = cell
            changed += 1

    with open(ITEMS_JSON, "w", encoding="utf-8") as f:
        json.dump(items, f, indent="\t", ensure_ascii=False)
        f.write("\n")

    print(f"\nPatched {changed}/{len(items)} items in items.json")
    print(f"Output dir: {HIRES_DIR}\n")
    print("Replace the sheet PNGs with real art (same grid layout, same 64×64 tile size)")
    print("and the game will automatically use the new icons — no further changes needed.")


if __name__ == "__main__":
    main()
